#!/usr/bin/env perl
use strict;

my @output = ("\n");

my $test = `perl -e 'use Perl::Critic;' 2>&1`;
push @output, "WHINGES:\n" if $test;   # something "wrong" with Critic's modules

my $cmd = 'use Perl::Critic;
use strict;

my $file = "'.$ARGV[0].'";
my $critic = Perl::Critic->new( -severity => "'.($ARGV[1]||5).'" );
my @violations = $critic->critique($file);
if (@violations) {
    print "\nVIOLATIONS:\n";
    print $_ foreach @violations;
    print "\n";
} else {
    print "\nNo violations.\n";
}
';

push @output, `perl -e '$cmd' 2>&1`;
print @output;  # doing it this way so that all output appears at once -- visually smoother
exit;
