#!/usr/bin/env perl
use strict;

my ($in, $out, $width) = @ARGV;

# WIDTH IS FLANK WIDTH -- NOT FINAL WINDOW WIDTH!!!
# RESULTING WINDOWS ALWAYS HAVE ODD LENGTH!!!

open IN, $in or die "Input file '$in' cannot be read: $!\n";
open OUT, "> $out" or die "Output file '$out' cannot be read: $!\n";
while (<IN>) {
    $_ =~ s/[\n\r]+$//;
    my @data = split /\t/, $_;
    $data[2] = $data[1]+$width+1;
    $data[1] = $data[1]-$width;
    print OUT join("\t",@data), "\n"; 
}
close OUT;
close IN;
exit;
