#!/usr/bin/env Rscript

source("/home/apa/apa_tools.R")

## ca <- c( "controls.all.basecall_table.txt", "../data/output/ADAR/ADAR.aligned.sorted.basecallsA.txt.gz", "../data/output/PADAR/PADAR.aligned.sorted.basecallsA.txt.gz", "../data/output/ADAR2/ADAR2.aligned.sorted.basecallsA.txt.gz", "../data/output/PADAR2/PADAR2.aligned.sorted.basecallsA.txt.gz" )

## ca <- c( "controls.unq.basecall_table.txt", "../data/output/ADAR/ADAR.aligned.reliable.sorted.basecallsA.txt.gz", "../data/output/PADAR/PADAR.aligned.reliable.sorted.basecallsA.txt.gz", "../data/output/ADAR2/ADAR2.aligned.reliable.sorted.basecallsA.txt.gz", "../data/output/PADAR2/PADAR2.aligned.reliable.sorted.basecallsA.txt.gz" )

if (!exists("ca")) ca <- commandArgs(trailing=TRUE)
outfile <- ca[1]
infiles <- ca[2:length(ca)]

N <- length(infiles)
names(infiles) <- extract.names.from.paths(infiles)

dat <- lapply(infiles, function(x) {
    if (grepl("\\.gz$",x)) {
        read.delim(gzfile(x),as.is=TRUE)[,1:8]
    } else {
        read.delim(gzfile(x),as.is=TRUE)[,1:8]
    }
})

utpr <- rownameless(unique(do.call(rbind, lapply(dat,"[",,1:3))))
utpr <- utpr[order(utpr[,1],utpr[,2]),]
colnames(utpr) <- c("TRANSCRIPT","POS","REF")
utp <- paste0(utpr[,1],".",utpr[,2])

dat2 <- lapply(dat, function(x) {
    y <- paste0(x[,1],".",x[,2])
    x[match(utp,y),4:8]
})

out <- rownameless(do.call(cbind, c(list(utpr), dat2)))
write.table2(out, outfile)
system(paste("gzip -f",outfile))
message("multisample_basecall_table ",outfile," complete!")
quit()
